-- Script to remove data generated by the seeder

-- 1. Remove related data in public tables first (to avoid orphan records if cascades aren't perfect)
DELETE FROM public.short_links
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

DELETE FROM public.inquiries
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

DELETE FROM public.properties 
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

DELETE FROM public.subscriptions
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

DELETE FROM public.verification_requests
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

DELETE FROM public.support_tickets
WHERE company_id IN (SELECT id FROM public.companies WHERE slug LIKE 'test-company-%');

-- 2. Remove the companies
DELETE FROM public.companies 
WHERE slug LIKE 'test-company-%';

-- 3. Remove the users from auth system
DELETE FROM auth.users 
WHERE email LIKE 'testuser_%';

-- 4. Clean up any related roles
DELETE FROM public.user_roles
WHERE user_id NOT IN (SELECT id FROM auth.users);
